### ISSUE TITLE
Small security issue

### ISSUE THREAD

**Issue by snyff** [OADA/oada-trusted-jws-js#2]
Hi, 

I discovered a tiny security issue with this package, what is the best way to report it?

Best,
Louis

**Comment by aultac** [comment]
Thanks!!  Please email details to aaron@openag.io so we can take a look.

**Comment by snyff** [comment]
done, the email comes from my work email: louis@pent...

**Comment by dukeofdisaster** [comment]
Any update on this?

**Comment by aultac** [comment]
Yes, thanks to @snyff for the heads up.  The issue was that the library fetches the jku URL on a signature even if that signature is considered untrusted.  As stated in the readme, this library is deprecated now in favor of https://github.com/oada/oada-certs.  The issue has been fixed there and published.
